
-- Incentive Hotel Finder v22 / Supabase setup
create table if not exists public.users (
  employee_id text primary key,
  name text,
  department text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.quotes (
  id text primary key,
  event_name text not null default '',
  status text not null default '견적수신',
  hotel text not null,
  city text not null default '',
  cur text not null default 'USD',
  nights numeric not null default 0,
  r1 numeric not null default 0,
  rate1 numeric not null default 0,
  r2 numeric not null default 0,
  rate2 numeric not null default 0,
  guests numeric not null default 0,
  tax_pct numeric not null default 0,
  tax_flat numeric not null default 0,
  fee numeric not null default 0,
  bf_pp numeric not null default 0,
  bf_days numeric not null default 0,
  porter numeric not null default 0,
  comp numeric not null default 0,
  comm numeric not null default 0,
  option_date date,
  note text not null default '',
  tax_incl boolean not null default false,
  fee_taxed boolean not null default false,
  bf_incl boolean not null default false,
  source text not null default 'manual',
  created_by text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quote_history (
  history_id bigint generated by default as identity primary key,
  quote_id text not null,
  action text not null,
  snapshot jsonb not null default '{}'::jsonb,
  changed_by text,
  changed_at timestamptz not null default now()
);

create index if not exists quotes_event_name_idx on public.quotes(event_name);
create index if not exists quotes_hotel_idx on public.quotes(hotel);
create index if not exists quote_history_quote_id_idx on public.quote_history(quote_id);

-- The browser never receives the service-role key; Netlify Functions use it server-side.
alter table public.users enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_history enable row level security;

-- Add allowed employees manually. Example:
-- insert into public.users(employee_id,name,department,active)
-- values ('H1234','홍길동','호텔공급부',true);


create table if not exists public.hotel_verifications (
  hotel_key text primary key,
  hotel_name text not null,
  city text not null default '',
  country text not null default '',
  official_name text,
  star_rating numeric,
  total_rooms numeric,
  largest_event_capacity numeric,
  official_url text,
  group_sales_email text,
  address text,
  notes text,
  sources jsonb not null default '[]'::jsonb,
  verified_at timestamptz not null default now(),
  verified_by text
);
create index if not exists hotel_verifications_city_idx on public.hotel_verifications(city);
alter table public.hotel_verifications enable row level security;
