-- V26: 도시 캐시 + 외부 호텔 캐시
create table if not exists public.cities (
  city_id bigint generated by default as identity primary key,
  city_name text not null,
  region text not null,
  country text,
  currency text,
  latitude double precision not null,
  longitude double precision not null,
  zoom integer default 11,
  source_type text default 'manual_seed',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(city_name, region)
);

create table if not exists public.hotel_discovery_cache (
  cache_id bigint generated by default as identity primary key,
  city_name text not null,
  region text not null,
  hotel_name text not null,
  latitude double precision,
  longitude double precision,
  star_rating numeric,
  area_name text,
  website text,
  phone text,
  email text,
  osm_id text,
  cached_at timestamptz not null default now(),
  unique(city_name, region, hotel_name)
);

create index if not exists cities_name_region_idx
  on public.cities(city_name, region);

create index if not exists hotel_discovery_cache_city_region_idx
  on public.hotel_discovery_cache(city_name, region);

alter table public.cities enable row level security;
alter table public.hotel_discovery_cache enable row level security;

-- 주요도시 39개 seed
insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('방콕','동남아','태국','THB',13.7563,100.5018,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('푸켓','동남아','태국','THB',7.8804,98.3923,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('다낭','동남아','베트남','USD',16.0544,108.2022,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('나트랑','동남아','베트남','USD',12.2388,109.1967,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('하노이','동남아','베트남','USD',21.0278,105.8342,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('호치민','동남아','베트남','USD',10.8231,106.6297,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('싱가포르','동남아','싱가포르','SGD',1.3521,103.8198,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('발리','동남아','인도네시아','USD',-8.4095,115.1889,10,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('세부','동남아','필리핀','USD',10.3157,123.8854,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('코타키나발루','동남아','말레이시아','MYR',5.9804,116.0735,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('도쿄','일본','일본','JPY',35.6762,139.6503,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('오사카','일본','일본','JPY',34.6937,135.5023,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('후쿠오카','일본','일본','JPY',33.5904,130.4017,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('오키나와','일본','일본','JPY',26.3344,127.8056,10,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('삿포로','일본','일본','JPY',43.0618,141.3545,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('나고야','일본','일본','JPY',35.1815,136.9066,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('뉴욕','미주','미국','USD',40.7128,-74.006,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('로스앤젤레스','미주','미국','USD',34.0522,-118.2437,10,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('샌프란시스코','미주','미국','USD',37.7749,-122.4194,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('라스베가스','미주','미국','USD',36.1699,-115.1398,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('시애틀','미주','미국','USD',47.6062,-122.3321,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('밴쿠버','미주','캐나다','CAD',49.2827,-123.1207,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('괌','남태평양','미국령 괌','USD',13.4443,144.7937,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('사이판','남태평양','미국령 북마리아나','USD',15.1778,145.7509,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('호놀룰루','남태평양','미국 하와이주','USD',21.3099,-157.8581,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('마우이','남태평양','미국 하와이주','USD',20.7984,-156.3319,10,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('시드니','남태평양','호주','AUD',-33.8688,151.2093,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('멜버른','남태평양','호주','AUD',-37.8136,144.9631,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('골드코스트','남태평양','호주','AUD',-28.0167,153.4,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('오클랜드','남태평양','뉴질랜드','NZD',-36.8509,174.7645,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('퀸스타운','남태평양','뉴질랜드','NZD',-45.0312,168.6626,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('프라하','유럽','체코','EUR',50.0755,14.4378,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('부다페스트','유럽','헝가리','EUR',47.4979,19.0402,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('비엔나','유럽','오스트리아','EUR',48.2082,16.3738,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('파리','유럽','프랑스','EUR',48.8566,2.3522,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('런던','유럽','영국','GBP',51.5074,-0.1278,10,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('로마','유럽','이탈리아','EUR',41.9028,12.4964,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('타이베이','중화권','대만','TWD',25.033,121.5654,12,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

insert into public.cities
(city_name,region,country,currency,latitude,longitude,zoom,source_type)
values ('홍콩','중화권','홍콩','HKD',22.3193,114.1694,11,'manual_seed')
on conflict (city_name,region) do update set
country=excluded.country,
currency=excluded.currency,
latitude=excluded.latitude,
longitude=excluded.longitude,
zoom=excluded.zoom,
updated_at=now();

